// Code generated by MockGen. DO NOT EDIT.
// Source: http_client.go
//
// Generated by this command:
//
//	mockgen -source=http_client.go -destination=http_client_mock.go
//

// Package mock_httpclient is a generated GoMock package.
package httpclient

import (
	http "net/http"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	DoFunc func(req *http.Request) (*http.Response, error)
}

// Do implements HTTPClient interface.
func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	return m.DoFunc(req)
}
