name: Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'GitHub User'

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Greet
      run: echo "Hello, ${{ github.event.inputs.name }}! This is a test workflow."
